FROM docker.io/library/maven:3.8.6-jdk-11 as builder
WORKDIR /usr/src/app
COPY src ./src
COPY pom.xml ./
RUN mvn -f ./pom.xml clean package

#FROM openjdk:11
FROM arindamgb/openjdk11-alpine3.16
WORKDIR /usr/app
COPY --from=builder /usr/src/app/target/hello-world-0.0.1-SNAPSHOT.jar ./
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/app/hello-world-0.0.1-SNAPSHOT.jar"]

