FROM docker.io/arindamgb/openjdk11-alpine3.16
COPY /home/runner/work/ab-java-project/ab-java-project/target/hello-world-0.0.1-SNAPSHOT.jar /usr/app/hello-world-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/app/hello-world-0.0.1-SNAPSHOT.jar"]
